@startuml

== initialization ==

loop mrX and up to 4 detectives
  gameController -> startPositionService: getStartPosition
  gameController <-- startPositionService: startPosition
  gameController -> ticketService: getTickets
  gameController <-- ticketService: tickets
  alt mrX or detective
    gameController -> mrXService: initialize(startPosition, tickets)
    gameController <-- mrXService: set up
  else
    gameController -> detectiveService: initialize(startPosition, tickets)
    gameController <-- detectiveService: set up
  end
end

== repetition ==

loop up to 21 turns or a detective catches mrX

  gameController -> mrXService: doNextMove
  gameController <-- mrXService: tickets

  loop up to 4 detectives
    gameController -> detectiveService: doNextMove
    gameController <-- detectiveService: ticket
    gameController -> mrXService: handOver(ticket)
    gameController <-- mrXService
  end

end

@enduml